project:
  type: website

website:
  title: "The impact of mental health on the community"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - sandstone
      - brand
    mainfont: arial
    fontsize: 1.5rem
    fontcolor: "#0013d5"
    css: styles.css
    toc: true

editor: visual

output-dir: docs